version: '3.3'
services:
  handler:
    build: ./handler
    image: handler
    depends_on:
      - event-store
      - minio

  inspector:
    build: ./inspector
    image: publisher
    restart: always
    ports:
      - '8001:8001'
    depends_on:
      - minio

  publisher:
    build: ./publisher
    image: publisher
    ports:
      - '8002:8002'
    depends_on:
      - event-store

    reverseproxy:
        image: nginx
        volumes:
          - .:/usr/share/nginx/html
        ports:
            - 8080:8080
            - 8081:8081
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always


  event-store:
    image: confluentinc/cp-kafka:5.4.1
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://event-store:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper:latest
    restart: always

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - minio-handler